ConfigItems = {
	enabled = true,
	items = {
		-- Tiendas generales
		{
			item = "bag_candy",
			label = "Bolsa de caramelos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una bolsa llena de caramelos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "canned_worms",
			label = "Gusanos en lata",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una lata con gusanos, útil como cebo.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_apple_candy",
			label = "Caramelo de manzana",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un dulce con sabor a manzana.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_beef_jerky",
			label = "Cecina de res",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne seca y salada, perfecta para el camino.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_biscuit_box",
			label = "Caja de galletas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una caja con galletas para picar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_coffee_gnds_reg",
			label = "Café molido (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Café molido enlatado para preparar una buena taza.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_cornedbeef",
			label = "Carne en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne enlatada lista para comer.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_crackers",
			label = "Galletas saladas (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Galletas saladas conservadas en lata.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_fruitsalad_can",
			label = "Ensalada de frutas (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Fruta variada en conserva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_kidneybeans",
			label = "Judías rojas (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Judías rojas enlatadas, nutritivas y fáciles de llevar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_peaches",
			label = "Melocotones (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Melocotones en conserva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_pear",
			label = "Peras (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Peras en conserva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_salmon",
			label = "Salmón (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Salmón enlatado.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_schmitz_salmon",
			label = "Salmón Schmitz (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Salmón en conserva de la marca Schmitz.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_strawberries_can",
			label = "Fresas (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Fresas en conserva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_can_sweet_corn",
			label = "Maíz dulce (lata)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Maíz dulce en conserva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_candy_oldfashion_rockcandy1",
			label = "Caramelo de roca (clásico) I",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un caramelo duro de estilo clásico.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_candy_oldfashion_rockcandy2",
			label = "Caramelo de roca (clásico) II",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un caramelo duro de estilo clásico.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_candy_oldfashion_rockcandy3",
			label = "Caramelo de roca (clásico) III",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un caramelo duro de estilo clásico.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_crackers",
			label = "Galletas saladas",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Galletas saladas para calmar el hambre.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_peanuts_roasted",
			label = "Cacahuetes tostados",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cacahuetes tostados, crujientes y sabrosos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_apple_caramel",
			label = "Manzana acaramelada",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una manzana cubierta de caramelo dulce.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_spice_seasoning",
			label = "Condimento de especias",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una mezcla de especias para cocinar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_water_filtered",
			label = "Agua filtrada",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Agua limpia y lista para beber.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "hair_pomade",
			label = "Pomada para el cabello",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pomada para peinar y dar brillo al cabello.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "schocolate_bar_dark",
			label = "Tableta de chocolate negro",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Chocolate negro con sabor intenso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "schocolate_bar_milk",
			label = "Tableta de chocolate con leche",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Chocolate con leche, dulce y suave.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "sold_fashioned_candy_box",
			label = "Caja de caramelos clásicos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una caja surtida de caramelos de estilo clásico.",
			degradation = 0,
			weight = 0.25,
		},

		-- Tabernas
		{
			item = "consumable_alcohol_beer_glass_amber",
			label = "Cerveza ámbar (vaso)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un vaso de cerveza ámbar bien fría.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_beer_pint",
			label = "Cerveza (pinta)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una pinta de cerveza para brindar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_raspberry_ale",
			label = "Cerveza de frambuesa",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una ale con un toque dulce de frambuesa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_whiskey",
			label = "Whisky",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un trago fuerte, ideal para calentar el cuerpo.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_gin",
			label = "Ginebra",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Destilado aromático, seco y contundente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_tequila",
			label = "Tequila",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un trago con carácter, directo al pecho.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_brandy",
			label = "Brandy",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Licor suave y cálido para una noche larga.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_cognac",
			label = "Coñac",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Coñac refinado, fuerte y con sabor intenso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_absinthe",
			label = "Absenta",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una bebida potente con un toque de anís.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_moscow_mule",
			label = "Moscow Mule",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cóctel fresco con un golpe de jengibre.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_coffee",
			label = "Café",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una taza de café para despejar la mente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_bottle_cola",
			label = "Cola (botella)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Bebida refrescante con burbujas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_bottle_cola_cherry",
			label = "Cola de cereza (botella)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cola con un toque dulce de cereza.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_bottle_sarsaparilla",
			label = "Sarsaparilla (botella)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Clásica bebida de sarsaparilla, dulce y espumosa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_bottle_soda_orange",
			label = "Soda de naranja (botella)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Refresco con sabor a naranja.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_juice_orange",
			label = "Zumo de naranja",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Zumo fresco y dulce de naranja.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_lemonade_strawberry",
			label = "Limonada de fresa",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Limonada refrescante con sabor a fresa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_oatmeal_plain",
			label = "Avena (simple)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un bol de avena caliente y sencilla.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_oatmeal_chocolatechip",
			label = "Avena con pepitas de chocolate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Avena caliente con pepitas de chocolate.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_soup_prison",
			label = "Sopa aguada",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una sopa pobre, pero al menos alimenta.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_fried_potato",
			label = "Patata frita",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Patata frita crujiente, recién hecha.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_bagel_egg_ham",
			label = "Bagel con huevo y jamón",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Bagel relleno de huevo y jamón, contundente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_plate_breakfast",
			label = "Plato de desayuno",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un desayuno completo para empezar el día.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_cheese_tray",
			label = "Tabla de carne y queso",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Surtido de carne y queso para compartir.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_beans_bacon",
			label = "Judías con tocino",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Judías calientes con trozos de tocino.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_fried_meal",
			label = "Comida frita",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un plato frito, grasiento pero sabroso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meatloaf",
			label = "Pastel de carne",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pastel de carne casero, tierno y lleno de sabor.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_steakpie",
			label = "Empanada de ternera",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Empanada caliente rellena de carne.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_ham_eggs_fries",
			label = "Jamón con huevos y patatas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Plato completo: jamón, huevos y patatas fritas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_orange_chicken",
			label = "Pollo a la naranja",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pollo con salsa dulce de naranja.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_mutton_cooked",
			label = "Cordero cocinado",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de cordero cocinada, jugosa y nutritiva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_alligator_cooked",
			label = "Carne de caimán cocinada",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de caimán cocinada, con sabor peculiar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_prime_beef_cooked",
			label = "Ternera de primera cocinada",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de primera, cocinada a la perfección.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_pie_peach2",
			label = "Tarta de melocotón",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Tarta dulce de melocotón, recién horneada.",
			degradation = 0,
			weight = 0.25,
		},

		-- Saloon
		{
			item = "consumable_alcohol_bourbon",
			label = "Bourbon",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un bourbon fuerte para una noche de saloon.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_rum",
			label = "Ron",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Ron especiado con un golpe cálido.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_wine_red",
			label = "Vino tinto",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una copa de vino tinto, intenso y aromático.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_wine_white",
			label = "Vino blanco",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una copa de vino blanco, suave y refrescante.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_sangria",
			label = "Sangría",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Sangría afrutada, dulce y fácil de beber.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_gin_tonic",
			label = "Gin tonic",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cóctel clásico, fresco y con carácter.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_martini_dry",
			label = "Martini seco",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Martini seco, elegante y potente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_mint_julip",
			label = "Julepe de menta",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cóctel fresco con menta y un toque dulce.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_clover_club",
			label = "Clover Club",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cóctel suave, afrutado y aromático.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_cocktail_last_word",
			label = "The Last Word",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cóctel equilibrado con final intenso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_alcohol_espresso_martini",
			label = "Martini espresso",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Café y licor en un trago con energía.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_tea_black",
			label = "Té negro",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Té negro caliente, fuerte y reconfortante.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_tea_lemon",
			label = "Té con limón",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Té suave con un toque cítrico de limón.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_tea_wild_berry",
			label = "Té de frutos del bosque",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Té aromático con sabor a frutos del bosque.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_horchata",
			label = "Horchata",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Bebida dulce y refrescante de sabor suave.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_float_cola",
			label = "Helado con cola",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Refresco de cola con una bola de helado.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_float_cola_cherry",
			label = "Helado con cola de cereza",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cola de cereza con helado, dulce y cremoso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_soup_carrot",
			label = "Sopa de zanahoria",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Sopa caliente de zanahoria, suave y nutritiva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_soup_tomato",
			label = "Sopa de tomate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Sopa de tomate caliente, con sabor casero.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_soup_duck",
			label = "Sopa de pato",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Sopa contundente de pato, perfecta para recuperar fuerzas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chips_salsa",
			label = "Nachos con salsa",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Totopos crujientes acompañados de salsa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_french_fries",
			label = "Patatas fritas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Patatas fritas doradas, recién servidas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_oatmeal_banana_berry",
			label = "Avena con plátano y frutos rojos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Avena caliente con plátano y frutos rojos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_oatmeal_nuts_berry",
			label = "Avena con frutos secos y bayas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Avena con frutos secos y bayas para más energía.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_taco",
			label = "Taco",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Taco caliente, sabroso y fácil de comer.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_noodles_foxtail",
			label = "Fideos con cola de zorro",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Fideos en caldo con un ingrediente poco común.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chef_bacon_sandwich",
			label = "Sándwich de bacon",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Sándwich caliente con bacon crujiente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_hamburger_fries",
			label = "Hamburguesa con patatas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Hamburguesa jugosa acompañada de patatas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_fishnchips",
			label = "Pescado con patatas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pescado rebozado con patatas fritas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_spaggetti_meatballs",
			label = "Espaguetis con albóndigas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pasta con albóndigas, un clásico contundente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_fried_chicken_biscuits",
			label = "Pollo frito con panecillos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pollo frito crujiente con panecillos tiernos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_oysters_steamed",
			label = "Ostras al vapor",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Ostras al vapor, delicadas y sabrosas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chicken_mushroom_fricassee",
			label = "Fricasé de pollo y setas",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Guiso cremoso de pollo con setas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_pie_banana_cream",
			label = "Tarta de plátano con crema",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Postre dulce de plátano con crema suave.",
			degradation = 0,
			weight = 0.25,
		},

		-- Panaderías
		{
			item = "consumable_milkshake_vanilla",
			label = "Batido de vainilla",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Batido cremoso con sabor a vainilla.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_milkshake_chocolate",
			label = "Batido de chocolate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Batido espeso y dulce de chocolate.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_milkshake_strawberry",
			label = "Batido de fresa",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Batido cremoso con sabor a fresa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_milkshake_blueberry",
			label = "Batido de arándanos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Batido suave con sabor a arándanos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_milkshake_chocolate_mint",
			label = "Batido de chocolate y menta",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Batido de chocolate con un toque fresco de menta.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cake_lemon",
			label = "Pastel de limón",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pastel esponjoso con un toque cítrico de limón.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chocolate_chip_loaf",
			label = "Bizcocho con pepitas de chocolate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Bizcocho tierno con pepitas de chocolate.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_brownie_fudge",
			label = "Brownie de chocolate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Brownie denso con sabor intenso a chocolate.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cake_orange_ginger",
			label = "Pastel de naranja y jengibre",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pastel aromático con naranja y un toque de jengibre.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cake_tres_leches",
			label = "Pastel tres leches",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pastel suave empapado en tres tipos de leche.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cupcake_buttercream",
			label = "Cupcake de crema de mantequilla",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cupcake dulce con cobertura de crema de mantequilla.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cupcake_chocolate",
			label = "Cupcake de chocolate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cupcake esponjoso con sabor a chocolate.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cupcake_cherry_chocolate",
			label = "Cupcake de cereza y chocolate",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cupcake con chocolate y un toque dulce de cereza.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cinnamon_buns",
			label = "Rollitos de canela",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Rollitos tiernos con canela y glaseado.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_conchas_vanilla",
			label = "Conchas de vainilla",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pan dulce tipo concha con sabor a vainilla.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_scone_blueberry",
			label = "Scone de arándanos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Scone tierno con arándanos, perfecto con café.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cookie_raisin",
			label = "Galleta con pasas",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Galleta dulce con pasas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_cookie_fig_newtons",
			label = "Galletas de higo",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Galletas rellenas de pasta de higo.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_pretzel",
			label = "Pretzel",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pretzel salado, perfecto para picar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_sausage_roll",
			label = "Hojaldre de salchicha",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Hojaldre caliente relleno de salchicha.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_coffee_chocolate",
			label = "Café con chocolate",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Café caliente con un toque dulce de chocolate.",
			degradation = 0,
			weight = 0.25,
		},

		-- Granjas
		{
			item = "consumable_canned_corn",
			label = "Maíz en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Maíz en conserva, listo para comer o cocinar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_carrots",
			label = "Zanahorias en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Zanahorias en conserva para una comida rápida.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_vegetables",
			label = "Verduras en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mezcla de verduras en conserva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_dill_pickles",
			label = "Pepinillos al eneldo",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pepinillos en vinagre con eneldo.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_onion_pickles",
			label = "Cebollitas en vinagre",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cebollitas encurtidas, crujientes y ácidas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_pepper_pickles",
			label = "Pimientos en vinagre",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pimientos encurtidos con sabor intenso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_sweet_pickles",
			label = "Pepinillos dulces",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pepinillos encurtidos con toque dulce.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_sweet_spicy_pickles",
			label = "Pepinillos dulces y picantes",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pepinillos encurtidos con sabor dulce y picante.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_pickled_beets",
			label = "Remolacha encurtida",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Remolacha en vinagre, dulce y ácida.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_eggs_pickles2",
			label = "Huevos en vinagre",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Huevos encurtidos, un bocado fuerte pero útil.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_chicken",
			label = "Pollo en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pollo en conserva, práctico para viajar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_pork",
			label = "Cerdo en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de cerdo en conserva, lista para comer.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_vienna_sausage",
			label = "Salchichas en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Salchichas en conserva, fáciles de llevar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_potted_meat",
			label = "Carne en paté (conserva)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne en paté en conserva, ideal para untar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_fried_pork_skins",
			label = "Cortezas de cerdo (conserva)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cortezas de cerdo crujientes, muy calóricas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_offal",
			label = "Casquería",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un alimento fuerte; no es para todos los paladares.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_strawberries",
			label = "Fresas en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Fresas en conserva, dulces y listas para comer.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_canned_raspberries",
			label = "Frambuesas en conserva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Frambuesas en conserva con sabor dulce.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_jelly_apple",
			label = "Mermelada de manzana",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mermelada dulce de manzana.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_jelly_grape",
			label = "Mermelada de uva",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mermelada de uva, perfecta para pan y postres.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_jelly_peach",
			label = "Mermelada de melocotón",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mermelada de melocotón, dulce y aromática.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_jelly_raspberry",
			label = "Mermelada de frambuesa",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mermelada de frambuesa con sabor intenso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_wojape",
			label = "Wojape",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Salsa dulce tradicional hecha con bayas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_milk_bucket",
			label = "Cubo de leche",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Leche recién ordeñada, fresca y nutritiva.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chef_butter",
			label = "Mantequilla",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mantequilla para cocinar y preparar recetas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chef_cream",
			label = "Nata",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Nata para cocina, ideal para salsas y postres.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chef_cream_cheese",
			label = "Queso crema",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Queso crema para recetas y repostería.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_chef_tomato_sauce",
			label = "Salsa de tomate",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Salsa de tomate para cocinar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_honey",
			label = "Miel",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Miel dulce, perfecta para endulzar o comer sola.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_honey_wild",
			label = "Miel silvestre",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Miel silvestre, más aromática y natural.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_iced_tea_lemon",
			label = "Té helado de limón",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Té helado con limón, refrescante y suave.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_iced_tea_peach",
			label = "Té helado de melocotón",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Té helado con sabor a melocotón.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_iced_tea_red_ginseng",
			label = "Té helado de ginseng rojo",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Té helado con ginseng rojo para recuperar energía.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_water_raspberry",
			label = "Agua con frambuesa",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Agua saborizada con un toque de frambuesa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_water_filtered_used",
			label = "Agua filtrada (usada)",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Envase vacío o usado; ya no es potable.",
			degradation = 0,
			weight = 0.25,
		},

		-- Establos
		{
			item = "horse_brush",
			label = "Cepillo para caballo",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cepillo para limpiar y cuidar el pelaje del caballo.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "hay_cube",
			label = "Cubo de heno",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Alimento para el caballo, útil para mantenerlo fuerte.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "horse_apple",
			label = "Manzana para caballo",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una manzana fresca para alimentar a tu caballo.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "horse_carrot",
			label = "Zanahoria para caballo",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una zanahoria para mimar y alimentar a tu caballo.",
			degradation = 0,
			weight = 0.25,
		},

		-- Artesanos
		{
			item = "collector_spade",
			label = "Pala de recolector",
			limit = 1,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pala resistente para excavar y recolectar.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "tool_hammer_blacksmith",
			label = "Martillo de herrero",
			limit = 1,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Herramienta de herrería para forjar y trabajar metal.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "tool_hatchet",
			label = "Hacha de mano",
			limit = 1,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Hacha pequeña para cortar y trabajar madera.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "tool_heavy_pickaxe",
			label = "Pico pesado",
			limit = 1,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pico pesado para minería y trabajos duros.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "tool_lumber_axe",
			label = "Hacha de leñador",
			limit = 1,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Hacha grande para talar y cortar leña.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "item_revolverbarrel",
			label = "Cañón de revólver",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un revólver.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_revolvercylinder",
			label = "Tambor de revólver",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un revólver.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_revolverhandle",
			label = "Empuñadura de revólver",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un revólver.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_repeaterbarrel",
			label = "Cañón de repetidor",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un repetidor.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_repeaterreceiver",
			label = "Cajón de mecanismos de repetidor",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un repetidor.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_repeaterstock",
			label = "Culata de repetidor",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un repetidor.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_riflebarrel",
			label = "Cañón de rifle",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un rifle.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_riflereceiver",
			label = "Cajón de mecanismos de rifle",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un rifle.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_riflestock",
			label = "Culata de rifle",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar un rifle.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_shotgunbarrel",
			label = "Cañón de escopeta",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar una escopeta.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_shotgunstock",
			label = "Culata de escopeta",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Pieza de arma para montar o reparar una escopeta.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "item_casing",
			label = "Vaina",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Vaina de munición para fabricar o recargar.",
			degradation = 0,
			weight = 0.25,
		},

		-- Armeros
		{
			item = "ammo_arrow",
			label = "Flecha",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Flecha para arcos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_box_pistol",
			label = "Caja de munición de pistola",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja de munición para pistolas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_box_repeater",
			label = "Caja de munición de repetidor",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja de munición para armas repetidoras.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_box_revolver",
			label = "Caja de munición de revólver",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja de munición para revólveres.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_box_rifle",
			label = "Caja de munición de rifle",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja de munición para rifles.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_box_rifle_elephant",
			label = "Caja de munición para rifle de elefante",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja de munición de alto calibre.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_box_shotgun",
			label = "Caja de munición de escopeta",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja de munición para escopetas.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_dynamite",
			label = "Dinamita",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Explosivo potente para demolición o combate.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_molotov",
			label = "Cóctel molotov",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Arma incendiaria improvisada.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "ammo_tomahawk",
			label = "Tomahawk",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Hacha arrojadiza para combate cercano.",
			degradation = 0,
			weight = 0.25,
		},

		-- Cazadores
		{
			item = "consumable_meat_beef",
			label = "Carne de res",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de res, ideal para cocinar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_pork",
			label = "Carne de cerdo",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de cerdo, lista para cocinar.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_big_game",
			label = "Carne de caza mayor",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de caza mayor; nutritiva y consistente.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_game",
			label = "Carne de caza",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de caza para preparar en fogata.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_plump_bird",
			label = "Carne de ave jugosa",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne de ave; tierna y sabrosa.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "consumable_meat_stringy",
			label = "Carne correosa",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Carne dura; mejor cocinada a fuego lento.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "poor_pelt",
			label = "Piel (mala)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de baja calidad, útil para vender o fabricar.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "good_pelt",
			label = "Piel (buena)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de buena calidad, apreciada por artesanos.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "perfect_pelt",
			label = "Piel (perfecta)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel perfecta, de la mejor calidad.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_snake_generic_skin_star_1",
			label = "Piel de serpiente (1 estrella)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de serpiente de calidad baja.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_snake_generic_skin_star_2",
			label = "Piel de serpiente (2 estrellas)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de serpiente de buena calidad.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_snake_generic_skin_star_3",
			label = "Piel de serpiente (3 estrellas)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de serpiente de calidad excelente.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_pelt_coyote_star_1",
			label = "Piel de coyote (1 estrella)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de coyote de calidad baja.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_pelt_coyote_star_2",
			label = "Piel de coyote (2 estrellas)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de coyote de buena calidad.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_pelt_coyote_star_3",
			label = "Piel de coyote (3 estrellas)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Piel de coyote de calidad excelente.",
			degradation = 0,
			weight = 1.0,
		},

		-- Minería
		{
			item = "resource_bag_coal",
			label = "Saco de carbón",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un saco de carbón para fundición y forja.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_bag_rock",
			label = "Saco de roca",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Roca recolectada para procesar o construir.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_bag_nitrite",
			label = "Saco de nitrito",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Mineral útil para procesos y fabricación.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_clay",
			label = "Arcilla",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Arcilla para artesanía y construcción.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_iron_bar",
			label = "Lingote de hierro",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Lingote de hierro refinado para forja.",
			degradation = 0,
			weight = 1.0,
		},
		{
			item = "resource_bag_copper",
			label = "Saco de cobre",
			limit = 50,
			can_remove = 1,
			type = "item_standard",
			usable = 0,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Cobre recolectado para fundición y fabricación.",
			degradation = 0,
			weight = 1.0,
		},

		-- Tabacaleras
		{
			item = "cigarette",
			label = "Cigarrillo",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un cigarrillo para fumar y relajarse.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "cigarette_box",
			label = "Cajetilla de cigarrillos",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una cajetilla con cigarrillos.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "cigarette_box_premium",
			label = "Cajetilla de cigarrillos premium",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una cajetilla de cigarrillos de calidad superior.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "cigar_strong",
			label = "Puro fuerte",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Un puro fuerte para los que aguantan el sabor.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "caja_de_puros",
			label = "Caja de puros",
			limit = 10,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Caja con varios puros.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "tobacco_chewing_regular",
			label = "Tabaco de mascar (suave)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Tabaco de mascar de sabor suave.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "tobacco_chewing_strong",
			label = "Tabaco de mascar (fuerte)",
			limit = 20,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Tabaco de mascar de sabor intenso.",
			degradation = 0,
			weight = 0.25,
		},
		{
			item = "pipe_p_pipe01x",
			label = "Pipa",
			limit = 1,
			can_remove = 1,
			type = "item_standard",
			usable = 1,
			useExpired = 0,
			groupId = 1,
			metadata = {},
			desc = "Una pipa para fumar tabaco.",
			degradation = 0,
			weight = 1.0,
		},
	},
}
